<?php

namespace LongevoModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * chamadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chamadosRepository extends EntityRepository
{
}
