<?php

namespace LongevoModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pedidosRepository extends EntityRepository
{
}
